export const CONCEPT_CATEGORY_CREATE_ERROR = 'CONCEPT_CATEGORY_CREATE_ERROR';
export const CONCEPT_CATEGORY_CREATE_SUCCESS = 'CONCEPT_CATEGORY_CREATE_SUCCESS';

export const CONCEPT_CATEGORY_DELETE_ERROR = 'CONCEPT_CATEGORY_DELETE_ERROR';
export const CONCEPT_CATEGORY_DELETE_SUCCESS = 'CONCEPT_CATEGORY_DELETE_SUCCESS';

export const CONCEPT_CATEGORY_UNDELETE_ERROR = 'CONCEPT_CATEGORY_UNDELETE_ERROR';

export const CONCEPT_CATEGORY_UPDATE_ERROR = 'CONCEPT_CATEGORY_UPDATE_ERROR';
export const CONCEPT_CATEGORY_UPDATE_SUCCESS = 'CONCEPT_CATEGORY_UPDATE_SUCCESS';

export const CONCEPT_CATEGORY_FILTERS = 'CONCEPT_CATEGORY_FILTERS';
export const CONCEPT_CATEGORY_LOADS_SUCCESS = 'CONCEPT_CATEGORY_LOADS_SUCCESS';
export const CONCEPT_CATEGORY_UNLOADS_SUCCESS = 'CONCEPT_CATEGORY_UNLOADS_SUCCESS';
