export const CONCEPT_QUESTION_CREATE_ERROR = 'CONCEPT_QUESTION_CREATE_ERROR';
export const CONCEPT_QUESTION_CREATE_SUCCESS = 'CONCEPT_QUESTION_CREATE_SUCCESS';

export const CONCEPT_QUESTION_DELETE_ERROR = 'CONCEPT_QUESTION_DELETE_ERROR';
export const CONCEPT_QUESTION_DELETE_SUCCESS = 'CONCEPT_QUESTION_DELETE_SUCCESS';

export const CONCEPT_QUESTION_UNDELETE_ERROR = 'CONCEPT_QUESTION_UNDELETE_ERROR';

export const CONCEPT_QUESTION_UPDATE_ERROR = 'CONCEPT_QUESTION_UPDATE_ERROR';
export const CONCEPT_QUESTION_UPDATE_SUCCESS = 'CONCEPT_QUESTION_UPDATE_SUCCESS';

export const CONCEPT_QUESTION_FILTERS = 'CONCEPT_QUESTION_FILTERS';
export const CONCEPT_QUESTION_READ_LIST_SUCCESS = 'CONCEPT_QUESTION_READ_LIST_SUCCESS';
export const CONCEPT_QUESTION_UNLOADS_SUCCESS = 'CONCEPT_QUESTION_UNLOADS_SUCCESS';